Models/Empleado.cs
namespace CrudASP.Models
{
    public class Empleado
    {
        public int IdEmpleado { get; set; }
        public string Nombre { get; set; }
        public string Email { get; set; }
        public DateOnly FechaContrato { get; set; }
        public bool Estado { get; set; }

    }
}

Models/ErrorViewModel.cs
namespace CrudASP.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/EmpleadoController.cs
using Microsoft.AspNetCore.Mvc;
using CrudASP.Data;
using CrudASP.Models;
using Microsoft.EntityFrameworkCore;
namespace CrudASP.Controllers
{
    public class EmpleadoController : Controller
    {
        private readonly AppDataContext _context;

        public EmpleadoController(AppDataContext context)
        {
            _context = context;
        }

        [HttpGet]
        public async Task<IActionResult> Lista()
        {
            List<Empleado> lista = await _context.Empleados.ToListAsync();
            return View(lista);
        }
        [HttpGet]
        public IActionResult Crear()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Crear(Empleado empleado)
        {
            if (ModelState.IsValid)
            {
                await _context.Empleados.AddAsync(empleado);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Lista));
        }

        [HttpGet]
        public async Task<IActionResult> Editar(int id)
        {
            Empleado empleado = await _context.Empleados.FirstAsync(e => e.IdEmpleado == id);
            return View(empleado);
        }

        [HttpPost]
        public async Task<IActionResult> Editar(Empleado empleado)
        {
            if (ModelState.IsValid)
            {
                _context.Empleados.Update(empleado);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Lista));
        }

        [HttpGet]
        public async Task<IActionResult> Eliminar(int id)
        {
            Empleado empleado = await _context.Empleados.FirstAsync(e => e.IdEmpleado == id);
            _context.Empleados.Remove(empleado);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Lista));
        }
    }
}

Controllers/HomeController.cs
using CrudASP.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CrudASP.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Empleado/Crear.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model CrudASP.Models.Empleado;

<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h2>Crear Empleado</h2>
        <form method="post" asp-controller="Empleado" asp-action="Crear">
            <div class="mb-3">
                <label>Nombre Completo</label>
                <input type="text" class="form-control" asp-for="Nombre" />
            </div>
            <div class="mb-3">
                <label>Email</label>
                <input type="text" class="form-control" asp-for="Email" />
            </div>
            <div class="mb-3">
                <label>Fecha Contrato</label>
                <input type="date" class="form-control" asp-for="FechaContrato" />
            </div>
            <div class="mb-3">
                <input type="checkbox" class="form-check-input" asp-for="Estado" id="chkEstado"/>
                <label class="form-check-label" for="chkEstado">Estado</label>
            </div>
            <div class="mb-3">
                <button type="submit" class="btn btn-primary">Guardar</button>
                <a asp-controller="Empleado" asp-action="Lista" class="btn btn-warning">Volver</a>
            </div>
        </form>
    </div>
</div>

Views/Empleado/Editar.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model CrudASP.Models.Empleado;
<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h2>Editar Empleado</h2>
        <form method="post" asp-controller="Empleado" asp-action="Editar">
            <input type="hidden" asp-for="IdEmpleado" />
            <div class="mb-3">
                <label>Nombre Completo</label>
                <input type="text" class="form-control" asp-for="Nombre" />
            </div>
            <div class="mb-3">
                <label>Email</label>
                <input type="text" class="form-control" asp-for="Email" />
            </div>
            <div class="mb-3">
                <label>Fecha Contrato</label>
                <input type="date" class="form-control" asp-for="FechaContrato" />
            </div>
            <div class="mb-3">
                <input type="checkbox" class="form-check-input" asp-for="Estado" id="chkEstado" />
                <label class="form-check-label" for="chkEstado">Estado</label>
            </div>
            <div class="mb-3">
                <button type="submit" class="btn btn-primary">Guardar</button>
                <a asp-controller="Empleado" asp-action="Lista" class="btn btn-warning">Volver</a>
            </div>
        </form>
    </div>
</div>

Views/Empleado/Lista.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model List<CrudASP.Models.Empleado>;

<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h2>Lista de Empleado</h2>
        <a asp-controller="Empleado" asp-action="Crear" class="btn btn-success mb-3">Crear Empleado</a>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <td>Id</td>
                    <td>Nombre Completo</td>
                    <td>Email</td>
                    <td>Fecha Contrato</td>
                    <td>Estado</td>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.IdEmpleado</td>
                        <td>@item.Nombre</td>
                        <td>@item.Email</td>
                        <td>@item.FechaContrato.ToString("dd/MM/yyyy")</td>
                        <td>@(item.Estado ? "Si" : "No")</td>
                        <td>
                            <a asp-controller="Empleado" asp-action="Editar" asp-route-id="@item.IdEmpleado" class="btn btn-primary mb-3">Editar</a>
                            <a asp-controller="Empleado" asp-action="Eliminar" asp-route-id="@item.IdEmpleado" Oneclick="return ConfirmarEliminar()" class="btn btn-danger mb-3">Eliminar</a>
                        </td>
                    </tr>
                }
                </tbody>
            </table>
    </div>
</div>

@section Scripts {
    <script>
        function ConfirmarEliminar() {
            return confirm("¿Está seguro de eliminar el registro?");
        }
    </script>
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CrudASP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CrudASP.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CrudASP</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - CrudASP - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>